name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: "Set up JDK 11"
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: "Setting up Maven Central authentication"
        uses: s4u/maven-settings-action@v2
        with:
          servers: '[{"id": "central", "username": "${env.MAVEN_USER}", "password": "${env.MAVEN_TOKEN}"}]'
          githubServer: false

      - name: "Build with Maven"
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
        run: mvn -X --batch-mode --update-snapshots verify
