name: Create Release on Semantic Version Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: a stable version to use (e.g. 1.2.1)

jobs:
  release:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDKs 8, 11, 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: |
            8
            17
            11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew -Pversion=${{ inputs.version }} build publishToMavenLocal
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSPHRASE }}


      - name: "Create release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ~/.m2/repository/io/github/pixee/java-security-toolkit/${{ inputs.version }}/java-security-*
